[package]
name = "twitchterm"
version = "0.1.0"
edition = "2021"

[dependencies]
irc = "1.0.0"
ratatui = "0.27.0"
reqwest = "0.12.5"
termwiz = "0.22.0"
tokio = { version = "1.38.1", features = ["full"] }
twitch-irc = "5.0.1"

